name: Python package (Conda)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: test-env
          environment-file: environment.yml
          python-version: 3.10

      - name: Install dependencies
        run: |
          conda install --file requirements.txt

      - name: Run tests
        run: |
          pytest
